name: CI

on:
  pull_request:
    branches: [main]
  workflow_call: {}

jobs:
  run-ci:
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v5

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: |
            3.8
            3.9
            3.10
            3.11

      - name: Install dependencies
        run: |
          python -m pip install -U pip
          pip install tox

      - name: Run tests
        run: |
          tox -s false
